baseurl = "https://maxbru.net"
languageCode = "en-us"
title = "Maxime Brunet"
theme = "vncnt-hugo"

ignoreFiles = [ "\\.gitkeep$" ]
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT"]

_merge = "none"

[params]
  author = "Maxime Brunet"
  description = "About Maxime Brunet. Social Media and Contact."
  bio = "---"
  email = ""
  avatar = "images/avatars/max.jpg"
  favicon = "images/icons/favicon.ico"

  [params.contact]
    github = "https://github.com/maxbrunet"
    gitlab = "https://gitlab.com/maxbrunet"
    linkedin = "https://linkedin.com/in/maxbrunet/en"
